const products = [
    { name: 'Stylish Sunglasses', price: 29.99, description: 'Chic and trendy sunglasses to complement your outfit. 😎' },
    { name: 'Designer Handbag', price: 99.99, description: 'A luxurious handbag for the fashion-forward individual. 👜' },
    { name: 'Classic White T-Shirt', price: 19.99, description: 'A versatile t-shirt that goes with anything. 👕' },
    { name: 'Trendy Sneakers', price: 59.99, description: 'Comfortable and stylish sneakers for everyday wear. 👟' },
    { name: 'Floral Maxi Dress', price: 79.99, description: 'A beautiful maxi dress perfect for summer outings. 🌸' },
    { name: 'Chic Fedora Hat', price: 34.99, description: 'Elevate your look with this fashionable fedora. 🎩' },
    { name: 'Leather Jacket', price: 129.99, description: 'A classic leather jacket that adds edge to any outfit. 🧥' },
    { name: 'Skinny Jeans', price: 49.99, description: 'Tailored skinny jeans that provide a sleek silhouette. 👖' },
    { name: 'Elegant Watch', price: 199.99, description: 'An elegant watch to make a lasting impression. ⌚' },
    { name: 'Sporty Track Pants', price: 39.99, description: 'Perfect for workouts or lounging at home. 🏃‍♂️' },
    { name: 'Stylish Belt', price: 24.99, description: 'A fashionable belt that completes your outfit. 👖' },
    { name: 'Graphic Hoodie', price: 49.99, description: 'Stay cozy and stylish with this graphic hoodie. 🐾' },
    { name: 'Leather Boots', price: 119.99, description: 'Durable leather boots for any weather. 👢' },
    { name: 'Silk Scarf', price: 29.99, description: 'Add a touch of elegance with this silk scarf. 🧣' },
    { name: 'Casual Shorts', price: 34.99, description: 'Stay cool in these casual shorts. ☀️' },
    { name: 'Athletic Cap', price: 19.99, description: 'A comfortable cap for a sporty look. 🧢' },
    { name: 'Knitted Sweater', price: 59.99, description: 'A warm knitted sweater for chilly days. ❄️' },
    { name: 'Vintage Sunglasses', price: 39.99, description: 'Retro sunglasses that will make you stand out. 🕶️' },
    { name: 'Stylish Tote Bag', price: 44.99, description: 'A roomy tote bag for all your essentials. 👜' },
    { name: 'Flared Pants', price: 49.99, description: 'Trendy flared pants that add flair to your look. 🌟' },
    { name: 'Cozy Slippers', price: 29.99, description: 'Comfortable slippers for lounging at home. 🏡' },
    { name: 'Breezy Summer Dress', price: 54.99, description: 'Light and airy dress for summer fun. 🌞' },
    { name: 'Stylish Crop Top', price: 25.99, description: 'Show off your style with this trendy crop top. 🌈' },
    { name: 'Ankle Boots', price: 79.99, description: 'Chic ankle boots that go with everything. 👢' },
    { name: 'Fashionable Backpack', price: 39.99, description: 'A stylish backpack for everyday use. 🎒' },
    { name: 'Formal Blazer', price: 89.99, description: 'Sharp blazer for professional occasions. 💼' },
    { name: 'Cute Babydoll Dress', price: 64.99, description: 'A cute babydoll dress for a playful look. 🍭' },
    { name: 'Puffy Winter Coat', price: 149.99, description: 'Stay warm and fashionable with this winter coat. ❄️' },
    { name: 'Lightweight Windbreaker', price: 49.99, description: 'Perfect for breezy days. 🌬️' },
    { name: 'Athletic Leggings', price: 29.99, description: 'Comfortable leggings for workouts or casual wear. 🏋️‍♀️' },
    { name: 'Beach Sarong', price: 19.99, description: 'Essential beachwear for sunny days at the shore. 🏖️' },
    { name: 'Sparkly Statement Necklace', price: 34.99, description: 'Add some sparkle to your outfit with this necklace. 💎' },
    { name: 'Chunky Knit Beanie', price: 19.99, description: 'Keep warm with this stylish beanie. 🧶' },
    { name: 'Casual Flip-Flops', price: 14.99, description: 'Easy and comfortable flip-flops for the beach. 🩴' },
];

export default products;